
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace WorkingWithDates.Models
{
    public partial class Events
    {
        [Key]
        [Column("EventID")]
        public int EventId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime EndDate { get; set; }
    }
}