
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace WorkingWithDates.Models
{
    public partial class Movies
    {
        [Key]
        public int Id { get; set; }
        public TimeSpan? Duration { get; set; }
        public string Title { get; set; }
    }
}