// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.CompilerServices;
using WorkingWithDates.Classes;
using WorkingWithDates.LanguageExtensions;

#nullable disable

namespace WorkingWithDates.Models
{
    /// <summary>
    /// Mapped to Person1 in the DbContext OnModelCreating event
    /// </summary>
    public partial class Person : INotifyPropertyChanged
    {
        private DateTime? _birthDate;

        [Key]
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        [Column(TypeName = "date")]
        public DateTime? BirthDate
        {
            get => _birthDate;
            set
            {
                _birthDate = value;
                OnPropertyChanged();
            }
        }

        /// <summary>
        /// For desktop apps
        /// </summary>
        public string Age => BirthDate?.Age(DateTime.Now).YearsMonthsDays;

        public event PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

    }
}