
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace WorkingWithDates.Models
{
    public partial class Room
    {
        [Key]
        public int RoomIdentifier { get; set; }
        public int? Identifier { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? StartTime { get; set; }
    }
}