
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using WorkingWithDates.Models;

#nullable disable

namespace WorkingWithDates.Data.Configurations
{
    public class EventsConfiguration : IEntityTypeConfiguration<Events>
    {
        public void Configure(EntityTypeBuilder<Events> entity)
        {
            entity.HasKey(e => e.EventId)
                .HasName("PK__Events__7944C87058D762E2");
        }
    }
}
