
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using WorkingWithDates.Models;

#nullable disable

namespace WorkingWithDates.Data.Configurations
{
    public class SalesConfiguration : IEntityTypeConfiguration<Sales>
    {
        public void Configure(EntityTypeBuilder<Sales> entity)
        {
            entity.Property(e => e.SaleDate).HasDefaultValueSql("(getdate())");
        }
    }
}
